name: ABC package builder

on:
  release:
    types: [published]


jobs:
  packer:
    strategy:
      matrix:
        os: ['linux', 'amd64', 'arm64', 'windows']
    runs-on: ubuntu-latest
    steps:

      - name : clone ABC 
        uses: actions/checkout@v2

      - name: Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.2

      - name: Show directory before
        run:  ls ./ && echo $(pwd)


      # building go package based on os version - we use release tag for version
      - name: ABC Package for Linux and Darwin-amd64
        if: ${{matrix.os != 'windows' && matrix.os != 'arm64'}} 
        run: go build -o "abc-${{github.event.release.tag_name}}" -tags 'oss' ./cmd/abc/...
      
      - name: Package for Windows
        if: ${{matrix.os  == 'windows'}}
        run:  go build -o "abc-${{github.event.release.tag_name}}.exe" -tags 'oss' ./cmd/abc/...

      - name: Package for Darwin-Arm64
        if: ${{matrix.os  == 'arm64'}}
        run: go build -o "abc-${{matrix.os}}-${{github.event.release.tag_name}}" -tags 'oss' ./cmd/abc/...

      - name: show afer 
        run: ls -la && ls -la ./cmd/abc/


      # creating zip files for each os
      - name: Zip
        run: sudo apt -y update && sudo apt -y install zip
      
      - name: Packing into zip for Linux 
        if: ${{matrix.os == 'linux'}} 
        run: zip -r "abc-${{matrix.os}}-${{github.event.release.tag_name}}.zip" "abc-${{github.event.release.tag_name}}"

      - name: Packing into zip for windows
        if: ${{matrix.os  == 'windows'}}
        run: zip -r "abc-${{matrix.os}}-${{github.event.release.tag_name}}.zip" "abc-${{github.event.release.tag_name}}.exe"

      - name: Packing into zip for Darwin-arm64
        if: ${{matrix.os  == 'arm64'}}
        run: zip -r "abc-darwin-${{matrix.os}}-${{github.event.release.tag_name}}.zip" "abc-${{matrix.os}}-${{github.event.release.tag_name}}"

      - name: Packing into zip for Darwin-amd64
        if: ${{matrix.os == 'amd64'}} 
        run: zip -r "abc-darwin-${{matrix.os}}-${{github.event.release.tag_name}}.zip" "abc-${{github.event.release.tag_name}}"

      - name: show where we are
        run: echo $(pwd)

      # Uploading the package to it's release based on release tag
      - name: Upload binaries to release for Linux and windows
        if: ${{matrix.os != 'amd64' && matrix.os != 'arm64'}} 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.RELEASER}}
          file: "abc-${{matrix.os}}-${{github.event.release.tag_name}}.zip"
          asset_name: "abc-${{matrix.os}}-${{github.event.release.tag_name}}.zip"
          tag: ${{github.event.release.tag_name}}
      
      - name: Upload binaries to release for amd64 and arm64
        if: ${{matrix.os == 'amd64' || matrix.os == 'arm64' }} 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.RELEASER}}
          file: "abc-darwin-${{matrix.os}}-${{github.event.release.tag_name}}.zip"
          asset_name: "abc-darwin-${{matrix.os}}-${{github.event.release.tag_name}}.zip"
          tag: ${{github.event.release.tag_name}}
